steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/strapi-docker', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/strapi-docker']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'strapi-docker', '--image', 'gcr.io/$PROJECT_ID/strapi-docker', '--region', 'us-central1','--platform', 'managed', '--allow-unauthenticated', '--quiet']
images:
- gcr.io/$PROJECT_ID/strapi-docker